### ISSUE TITLE
Fail to install matscipy on Windows system

### ISSUE THREAD

**Issue by qqqqmmmm** [libAtoms/matscipy#102]
On Windows, when I execute "python setup.py build", it says 

c = os.path.basename(self.compiler.compiler[0])
AttributeError: 'MSVCCompiler' object has no attribute 'compiler'. Did you mean: 'compile'?

What should I do? Thanks

**Comment by pastewka** [comment]
We don't support Windows build. You are welcome to fix it, but we cannot offer support for Windows.

If you want to run matscipy on Windows, I recommend using [WSL](https://docs.microsoft.com/en-us/windows/wsl/install).
