### ISSUE TITLE
Build Wheels

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/matscipy#106]
I'd like to setup [cibuildwheel](https://cibuildwheel.readthedocs.io/en/stable/) to build binary wheels using GitHub Actions that we can release on PyPI. This would also help with issues like #57 requesting support on a wider range of platforms. I've had good success doing this with f90wrap and quippy, and matscipy should be simpler as there's no Fortran (although there is C++, so #96 would still be valuable).

**Comment by jameskermode** [comment]
@pastewka Is C++11 sufficient for everything we use? If not there are tricks to enable C++14 compliant compilers: https://cibuildwheel.readthedocs.io/en/stable/cpp_standards/

**Comment by pastewka** [comment]
The C++ parts are very bare bones, C++11 should be sufficient.

**Comment by jameskermode** [comment]
Done for MacOS and Linux in #107. Will leave this open until tested and as a reminder to add Windows support.

**Comment by ilyes319** [comment]
Hey @jameskermode,

Putting a comment here for the windows wheels. I am trying to install matscipy on windows. I think I am using MSVC compiler. When doing `pip install matscipy` I get the following error: 
[matscipy_error_pip.txt](https://github.com/libAtoms/matscipy/files/10076180/matscipy_error_pip.txt)

Not sure I understand correctly the error. Maybe the wheels does not work with MSVC and I should use GCC.

**Comment by jameskermode** [comment]
OK thanks. This is the same error I get in GitHub Actions so at least it's consistent.

**Comment by ilyes319** [comment]
The new windows wheel works great, but when I `import matscipy.neighbours` I get the following error: 
```Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\Lilyes\anaconda3\envs\torch_nightly\lib\site-packages\matscipy\neighbours.py", line 35, in <module>
    from . import ffi
  File "C:\Users\Lilyes\anaconda3\envs\torch_nightly\lib\site-packages\matscipy\ffi.py", line 38, in <module>
    from _matscipy import *  # noqa
ModuleNotFoundError: No module named '_matscipy'
```

**Comment by pastewka** [comment]
I think this could be related to moving the location of the extension module @prs513rosewood

**Comment by jameskermode** [comment]
Agreed, it look’s related to that change. Can we fix or revert please?

**Comment by prs513rosewood** [comment]
@ilyes319 Could you list your `site-packages\` and `site-packages\matscipy` directories? The changes I've made should pick up `_matscipy.*` installed in both of these locations.

**Comment by prs513rosewood** [comment]
I investigated a bit more and the true error message is the following:

```
Traceback (most recent call last):
  File "C:\Users\lucas\AppData\Roaming\Python\Python311\site-packages\matscipy\ffi.py", line 36, in <module>
    from ._matscipy import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^
ImportError: DLL load failed while importing _matscipy: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 2, in <module>
  File "C:\Users\lucas\AppData\Roaming\Python\Python311\site-packages\matscipy\ffi.py", line 38, in <module>
    from _matscipy import *  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_matscipy'
```

I looked into the DLL load failed error and the source could be either:

1) [Missing C++ runtime components](https://cibuildwheel.readthedocs.io/en/stable/faq/#windows-importerror-dll-load-failed-the-specific-module-could-not-be-found)
2) The compiled extension dynamically links to GCC libs that are missing, [which can happen with Meson](https://github.com/mesonbuild/meson/issues/10454)

After looking at the dependencies of the compiled extension, it seems the second option is more likely, since it links to `libgcc_s_seh-1.dll` and `libstdc++-6.dll`, so the error is unrelated to the location of the `_matscipy` module.

**Comment by prs513rosewood** [comment]
@ilyes319 The [latest wheels](https://github.com/libAtoms/matscipy/actions/runs/3740182068) should now work for windows.
