### ISSUE TITLE
Add pyproject.toml and potentials change build system

### ISSUE THREAD

**Issue by pastewka** [libAtoms/matscipy#116]
We should as a `pyproject.toml` file and at least switch to declarative `setuptools` build. My suggestion would be to additionally switch to `Meson` as a build environment, see here: https://thiblahute.gitlab.io/mesonpep517/pyproject.html

**Comment by jameskermode** [comment]
Good idea - this would probably help with the failing Windows builds too (see #106, currently preventing MACE from adding matscipy as a dependency despite a huge performance speed up from switching to our neighbour list).

**Comment by pastewka** [comment]
I'm not sure what Meson support for Windows is - should check. The only other build system I am aware of is `scikit-build` which uses CMake under the hood: https://scikit-build.readthedocs.io/en/latest/usage.html - However, Meson seems more modern and better designed.

**Comment by jameskermode** [comment]
Yes, I've also had a brief look at Meson and think it looks good. There's also [pants](https://www.pantsbuild.org/) but it's probably over-the-top for us.

**Comment by pastewka** [comment]
Never heard of pants, will look into it. But it looks like they don't support C-code at present.

**Comment by eli-schwartz** [comment]
> I'm not sure what Meson support for Windows is - should check.

Well, SciPy (and WIP for NumPy) is using Meson for Windows builds as well. :)

As far as pants goes, it seems like it's yet another bazel derivative? I question how that's supposed to work with `pip install` from an sdist, whereas Meson has a PEP 517 build backend (actually two of them, https://pypi.org/project/meson-python/ is a newer one that was built for SciPy).

**Comment by pastewka** [comment]
I've just switched another project over to Meson, it was fantatically simple: https://github.com/ContactEngineering/SurfaceTopography/pull/255 - will do the same for matscipy

**Comment by pastewka** [comment]
Closed with #117 , thanks for the great work @prs513rosewood and @jameskermode
