### ISSUE TITLE
New PyPI release

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/matscipy#146]
The current release fails with latest numpy and ASE, so we're overdue for a new one. Does anyone have anything they'd like to merge before we go ahead and do this? I think all the new wheels are working, so will be nice to get them on PyPI too.

**Comment by pastewka** [comment]
Please release, we should release much more often than we do anyway.

**Comment by Heeeeeeeero** [comment]
Hello, Could I ask where is the .tar.gz2 file of new released 0.8.0 version?

**Comment by jameskermode** [comment]
https://github.com/libAtoms/matscipy/releases/tag/v0.8.0

Sorry I missed this comment!
