### ISSUE TITLE
fail to install from github in github CI

### ISSUE THREAD

**Issue by bernstei** [libAtoms/matscipy#148]
I'm trying to set up a github CI that uses matscipy, and attempting to install using from the github repo fails, e.g. https://github.com/libAtoms/pymatnext/actions/runs/4779137831/jobs/8496016926

I'm going to try to reproduce outside the github CI.

**Comment by pastewka** [comment]
Looks like we need to add pure: false to the meson build file.

**Comment by bernstei** [comment]
If you try that, please post here and I'll trigger another run of the CI action in my repo that uses it.

**Comment by bernstei** [comment]
BTW, the reason I'm using the github HEAD is that there's an issue with a deprecated/unsupported use of `np.str` in `eam.io`, and the pypi version doesn't work, so tagging a new version would actually solve my immediate problem as well.

**Comment by pastewka** [comment]
Hi @bernstei - can you try out the 23_pure_builds branch, see PR here: https://github.com/libAtoms/matscipy/pull/149

**Comment by bernstei** [comment]
> @bernstei - the change has been merged into master

Thanks - I'll try another CI installation, and see if it fixes the issue.

**Comment by bernstei** [comment]
matscipy from github installation in the CI works fine now.  Thanks for the quick fix.

**Comment by bernstei** [comment]
fixed by #149 or #150, apparently.
