### ISSUE TITLE
Rotation in elastic_moduli

### ISSUE THREAD

**Issue by kbal** [libAtoms/matscipy#152]
In the function `elastic_moduli()`, defined in `elasticity.py`, a rotation of the vector `u_b` (based on the function argument `l`) into `u_a = np.array([1, 0, 0])` is performed. That is, the argument vector is rotated into the x direction. A crucial bit here is the cross product

`u_v = np.cross(u_a, u_b)`

If I am not mistaken, a rotation starting with this operation corresponds to a rotation of `u_a` into `u_b`, i.e., a rotation of the x-vector into the chosen direction. Therefore, I believe it is correcter to write

`u_v = np.cross(u_b, u_a)`

or swap the definitions of `u_a` and `u_b`. I spotted there is an inconsistency with the Young's moduli as predicted by ELATE, if directions such as [101] and [-101] are not equivalent. So in many higher-symmetry systems this issue won't show up. Making the proposed changes makes the issue go away.

**Comment by jameskermode** [comment]
Thanks for spotting this. A PR to fix it together with a test that demonstrates the error in the current implementation would be much appreciated!

**Comment by kbal** [comment]
Sorry for the late reply. I've created a pull request.
