### ISSUE TITLE
[JOSS Review] Documentation 

### ISSUE THREAD

**Issue by mbarzegary** [libAtoms/matscipy#186]
Dear authors,

The documentation of the software is nicely done, but you may consider improving it with these suggestions:
* Some of the mentioned functionalities of the package are not documented. For example, there is no documentation for the electrochemistry. Also, some of the atomic analysis tools and all the interatomic potential features are only documented via autogenerated API docs. I think this makes it hard for beginner users to get started with the package. The application domains (except the electrochemistry, as mentioned) are well documented and described. It can be beneficial to talk a little bit about the package features in the documentation.
* It's mentioned that the package has an interface to the FEniCS code. This functionality is supported by one example that does not run. FEniCS dependency is not documented and elaborated.

P.S. This issue is related to https://github.com/openjournals/joss-reviews/issues/5668

**Comment by pastewka** [comment]
@jotelha Can you please add documentation on the electrochemistry module? Maybe we can turn part of the example into a documentation of the module. Please also document the FEniCS coupling there.

**Comment by jotelha** [comment]
@pastewka I think I am done with the electrochemistry and CLI documentation pages on https://github.com/libAtoms/matscipy/pull/210 . Generating the docs from jupyter notebooks works very neatly!
