### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by cortner** [libAtoms/matscipy#2]
I get a compile error related to the `-std=c++0x` option (I think). Full output is below. 

This is on OS X 10.10.5, Anaconda Python 2.3.0, andApple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)

Sunrise:matscipy ortner$ CC=gcc CXX=g++ python setup.py build
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "_matscipy" sources
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
building '_matscipy' extension
compiling C sources
C compiler: gcc -fno-strict-aliasing -I/Users/ortner/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes

compile options: '-I/Users/ortner/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Users/ortner/anaconda/include/python2.7 -c'
extra options: '-std=c++0x'
gcc: c/tools.c
error: invalid argument '-std=c++0x' not allowed with 'C/ObjC'
error: invalid argument '-std=c++0x' not allowed with 'C/ObjC'
error: Command "gcc -fno-strict-aliasing -I/Users/ortner/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ortner/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Users/ortner/anaconda/include/python2.7 -c c/tools.c -o build/temp.macosx-10.5-x86_64-2.7/c/tools.o -std=c++0x" failed with exit status 1

**Comment by pastewka** [comment]
Oops, this is related to how different compiler handle C++11. James had looked at this in detail and probably knows the answer.

James, should we think about disabling the ring statistics part on some platforms?

Lars

Am 27.09.2015 10:15 vorm. schrieb Christoph Ortner <notifications@github.com>:

I get a compile error related to the -std=c++0x option (I think). Full output is below.

This is on OS X 10.10.5, Anaconda Python 2.3.0, andApple LLVM version 6.1.0 (clang-602.0.53) (based on LLVM 3.6.0svn)

Sunrise:matscipy ortner$ CC=gcc CXX=g++ python setup.py build
running build
running config_cc
unifing config_cc, config, build_clib, build_ext, build commands --compiler options
running config_fc
unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
running build_src
build_src
building extension "_matscipy" sources
build_src: building npy-pkg config files
running build_py
running build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
customize UnixCCompiler
customize UnixCCompiler using build_ext
building '_matscipy' extension
compiling C sources
C compiler: gcc -fno-strict-aliasing -I/Users/ortner/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes

compile options: '-I/Users/ortner/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Users/ortner/anaconda/include/python2.7 -c'
extra options: '-std=c++0x'
gcc: c/tools.c
error: invalid argument '-std=c++0x' not allowed with 'C/ObjC'
error: invalid argument '-std=c++0x' not allowed with 'C/ObjC'
error: Command "gcc -fno-strict-aliasing -I/Users/ortner/anaconda/include -arch x86_64 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/ortner/anaconda/lib/python2.7/site-packages/numpy/core/include -I/Users/ortner/anaconda/include/python2.7 -c c/tools.c -o build/temp.macosx-10.5-x86_64-2.7/c/tools.o -std=c++0x" failed with exit status 1

-

**Comment by jameskermode** [comment]
I've locally resolved this with Christoph but we still need a general solution. It seems C++11 is sufficiently well supported, the only problem is getting Python distutils to pass different flags when compiling C and C++ code, as passing ```-std-c++0``` with C input files causes errors with some compilers. Setting the ```CXXFLAGS``` environment variable should work, but doesn't because of this bug:
http://bugs.python.org/issue1222585

**Comment by jameskermode** [comment]
Should now be fixed. I had to delve deeper into numpy.distutils than I would like, but I've found a way to pass different options to C and C++ compilers which is working on our Travis-CI build slaves with g++ and clang++ and on Linux and OS X.  There are now dictionaries of C and C++ options at the top of setup.py that can be customised on a per-compiler basis if this issue recurs.

Christoph, it would be great if you could revert the local changes made to setup.py (with ```git checkout setup.py```) then pull again and check it now compiles out of the box for you with anaconda Python. I will then close the issue.

**Comment by cortner** [comment]
It builds and installs. If I run into any issues in usage, I'll open another report. Many thanks!
