### ISSUE TITLE
v0.8.1 and v0.9.0 releases

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/matscipy#215]
I would like to do a patch release v0.8.1 ASAP because installation of v0.8.0 currently on PyPI is broken on ppc but fixed in master. Any objections to doing this now? 

There are of course more outstanding PRs in the works, some of which provide new functionality sufficient to warrant a v0.9.0 release; perhaps this could be timed to accompany the JOSS paper since we are getting close to finishing everything for that.

**Comment by pastewka** [comment]
No objection

**Comment by jameskermode** [comment]
Great, I'll release v0.8.1 now, which will give another chance for conda-forge to fix itself, then we can prepare more carefully for v0.9.0.

**Comment by jameskermode** [comment]
Done - wheels are live at https://pypi.org/project/matscipy/0.8.1/

For some reason the Cirrus CI job doesn't run when a tag is created so I had to trigger that manually and uloaded the macos arm64 wheels.

**Comment by pastewka** [comment]
Great, thanks
