### ISSUE TITLE
Part of the electrochemistry module does not follow coding style

### ISSUE THREAD

**Issue by pastewka** [libAtoms/matscipy#216]
We adhere to PEP-8, which mentions "Function names should be lowercase, with words separated by underscores as necessary to improve readability." Part of the electrochemisty module uses CamelCase.

Example:
https://github.com/libAtoms/matscipy/blob/ba2179106680a102d4510d2be1bdf8374c3be645/matscipy/electrochemistry/poisson_nernst_planck_solver.py#L382

**Comment by pastewka** [comment]
@jotelha - can you have a look at this?

**Comment by jotelha** [comment]
Addressed in https://github.com/libAtoms/matscipy/pull/218
