### ISSUE TITLE
Calling neighborlist in C++

### ISSUE THREAD

**Issue by CheukHinHoJerry** [libAtoms/matscipy#246]
Thank you for the nice package. Is there an example (or is it possible) on how to call the neighborlist (as in Python) in C++? Would be more very nice since I need a fast neighborlist in certain C++ code.

**Comment by pastewka** [comment]
The neighbor list is closely tied to the Python C-API, which makes disentangling it for use with pure C/C++ difficult.

We have a pure C++ implementation (that we use mainly for teaching) here: https://pastewka.github.io/MolecularDynamics/_project/milestone06.html - Note that this implementation does not support periodic boundaries, which in our teaching code are implemented by copy a ghost region of atoms.

The individual files are:
* https://pastewka.github.io/MolecularDynamics/_project/neighbors.h
* https://pastewka.github.io/MolecularDynamics/_project/neighbors.cpp
* https://pastewka.github.io/MolecularDynamics/_project/test_neighbors.cpp

The  code is MIT-licensed. Feel free to use and reuse.

**Comment by pastewka** [comment]
PS: We have full C++ MD code, but that is not public (because of teaching). I'd be happy to share the full repository with you if interesting.

**Comment by CheukHinHoJerry** [comment]
Thank you very much for pointing out the references! I think I have happy with what I have access to right now. I will close the issue.
