### ISSUE TITLE
numpy 2

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/matscipy#248]
Current wheel building pipeline is failing as wheels are built with numpy 1 which is binary incompatible with numpy 2. We could either build with numpy 2 or add `numpy<2` constraint to the test environment. Thoughts?

**Comment by pastewka** [comment]
They changed the binary interface. I need to go through the C code an update. Should be straightforward.

**Comment by pastewka** [comment]
@jameskermode I misunderstood your question. The code runs fine with numpy 2.0. Should we just switch the whole thing to 2.0 (and at the same time deprecate Python 3.7)?

**Comment by jameskermode** [comment]
I'd be ok with this. Does latest ASE release also support numpy 2?

**Comment by pastewka** [comment]
It should be agnostic, as there is no binary. Not sure there were breaking changes. I'll see if tests runs okay with numpy 2, otherwise I'll limit numpy<2 for the time being.
