### ISSUE TITLE
New release after numpy2 fix

### ISSUE THREAD

**Issue by stefaanhessmann** [libAtoms/matscipy#264]
Dear developers,

recently, numpy2 caused problems with matscipy, which you seem to have already solved in #254.
Our software package depends on matscipy, which is automatically installed from pipy.
However, this means that we either stick with the old numpy versions, or install matscipy from source.

Are you planning to include this in a new pipy release (e.g. to v1.0.1) in the near future?
For us (and maybe for others?) this would be very helpful.

Thanks for the support,
Stefaan

**Comment by jameskermode** [comment]
Thanks for the heads up and the kind words. I'll do a release as soon as possible.

**Comment by jameskermode** [comment]
v1.1.0 has been tagged and should appear on PyPI in an hour or so once the wheels get build in CI
