### ISSUE TITLE
Unexpected Vacancy in Generating a Straight Edge Dislocation

### ISSUE THREAD

**Issue by Weixinyi-Cindy** [libAtoms/matscipy#265]
Dear developers,
I am currently using the matscipy.dislocation module to generate a BCC edge dislocation for tungsten with the following properties:
- The Burgers vector is (1,0,0).
- The direction of the dislocation line is (0,0,−1).
- The direction of the excess half atomic plane is (0,−1,0).

I utilized the following code to generate the edge dislocation: 

`
cylinder_r = 200
`
`
a0, C11, C12, C44 = get_elastic_constants("./potentials/w_eam4.fs", delta=1e-3)
`
`
dislocation = disl.BCCEdge100Dislocation(a0, C11, C12, C44)
`
`
bulk1, disloc_ini, disloc_fin = dislocation.build_glide_configurations(radius=cylinder_r)
`
`
u0 = disloc_ini.positions - bulk1.positions
`

The issue arises in the 2D image of disloc_ini.positions. Along the (-1,0,0) direction on the slip plane, an unexpected vacancy appears near R = 170, where R represents the distance to the dislocation core.

![edge dislocation1](https://github.com/user-attachments/assets/f725620c-bb3e-4123-927b-bca9498dad52)
![edge dislocation2](https://github.com/user-attachments/assets/4da5e108-20f3-4b4b-b79c-89e1f3a9a100)

It seems that along the (-1,0,0) direction on the slip plane, atoms with R < 170 are moving towards the dislocation core, while atoms with R > 170 are moving away from it, which creates the appearance of a "vacancy" near R = 170.

I tried using different values of cylinder_r (greater than 170), but the same issue persists near R = 170. I would appreciate guidance on how to resolve this problem. Thank you!

**Comment by jameskermode** [comment]
@thomas-rocke  could you take a look at this?

**Comment by Weixinyi-Cindy** [comment]
@jameskermode Thank you very much for your help!
@thomas-rocke Thank you very much for your detailed response. With the help of the program you provided, I was able to successfully generate the correct BCC dislocation configuration.

**Comment by thomas-rocke** [comment]
Hi @Weixinyi-Cindy ,
A more permanent fix for this issue is now available - I added an `r_sc` parameter to all of the cylinder construction functions, which controls how far away from the dislocation core we do the self-consistent solve for the dislocation displacements.

Setting `r_sc` to be less than the radius you see the vacancy at should remove it from the structure, for example:
```
bulk1, disloc_ini, disloc_fin = dislocation.build_glide_configurations(radius=200, r_sc=100)
```

**Comment by Weixinyi-Cindy** [comment]
@thomas-rocke Thank you very much for providing the permanent fix so quickly. With the fix you provided, I successfully solved my problem.

My work is to consider the equilibrium of an edge displacement near the origin, characterizing the properties of the equilibrium displacement $\bar{u}$.

Under suitable stability conditions, the $\bar{u}$ exhibits the following property:  
$\lVert D\bar{u}-D\bar{u}_R \lVert _{l^2} \lesssim R^{-1}logR$, for $R$ sufficiently large. 
Here, $\bar{u}_R$ represents the equilibrium displacement when atoms are fixed in their reference configurations outside a ball of radius $R$.

In numerical simulation, the equilibrium displacement of the edge dislocation with radius=500 was chosen as $\bar{u}$. Different values of $R$ were then used to calculate $\bar{u}_R$. The resulting convergence rate is shown in the figure below, consistent with the theoretical analysis.

![CR500](https://github.com/user-attachments/assets/84ba9654-eec4-4fe1-8f3f-69a9e1c967c4)


This result confirms that the configuration derived from the fix you provided is correct. I really appreciate your help!

**Comment by jameskermode** [comment]
Thanks for sharing your results, nice to know this now gives the expected convergence behaviour!
