### ISSUE TITLE
Neighbourlist needs bulk=true?

### ISSUE THREAD

**Issue by cortner** [libAtoms/matscipy#3]
```julia
push!(LOAD_PATH, "..")
using PyCall
using ASE
@pyimport matscipy.neighbours as matscipy_nlist
at = bulk("Al"; cubic=true)
at = repeat(at, (3, 3, 3))
@time NL = matscipy_nlist.neighbour_list("ijd", at.po, 3.1)
```
this returns neighbours as expected.

Changing to
```julia
at = bulk("Al"; cubic=false)
```
returns an empty neighbourlist. 
```julia
(Int32[],Int32[],Float64[])
```
(also, it takes 6.8 second instead of 0.02 seconds)

**Comment by pastewka** [comment]
Hi Christoph,
 
this looks like a bug, I’ll look into this. It should work with non-orthogonal cells.
 
Best,
Lars

**Comment by cortner** [comment]
Thank you! The list now returns something. (I haven't actually checked whether it returns the correct neighbours) I can do that later if useful.

**Comment by pastewka** [comment]
I you could test, that would be great. I'll mark this as resolved for the time being.

**Comment by cortner** [comment]
@pastewka I did a visual comparison with the ASE neighbour list and they match ok. So this seems indeed resolved.  Thank you, again.

**Comment by pastewka** [comment]
Great, thanks!

-------- Ursprüngliche Nachricht --------
Von: Christoph Ortner <notifications@github.com>
Datum: 28.09.2015 15:44 (GMT+01:00)
An: libAtoms/matscipy <matscipy@noreply.github.com>
Cc: "Pastewka, Lars (IAM)" <lars.pastewka@kit.edu>
Betreff: Re: [matscipy] Neighbourlist needs bulk=true? (#3)


@pastewka<https://github.com/pastewka> I did a visual comparison with the ASE neighbour list and they match ok. So this seems indeed resolved. Thank you, again.

-
