### ISSUE TITLE
elasticity doesn't know about symmetry constraint

### ISSUE THREAD

**Issue by bernstei** [libAtoms/matscipy#36]
It may not be worth fixing, so maybe it's just a "won't fix", but the ASE new FixSymmetry constraint confuses matscipy.elasticity.  If the constraint is applied when you start computing elastic constants, the strains that it thinks it's applying don't actually take effect, and you get garbage elastic constants as a result.  One consistent alternative is for matscipy to have a keep_symmetry argument, which applies a re-computed symmetry constraint after each strain but before the relaxation (so strains can break the symmetry but the relaxations cannot break it further).

**Comment by jameskermode** [comment]
How about simply raising an exception if the Atoms object passed into `fit_elastic_constants()` has any constraints attached?

**Comment by pastewka** [comment]
That sounds like a reasonable safeguard


________________________________
Von: James Kermode <notifications@github.com>
Gesendet: Freitag, 1. Mai 2020 10:49
An: libAtoms/matscipy
Cc: Subscribed
Betreff: Re: [libAtoms/matscipy] elasticity doesn't know about symmetry constraint (#36)

**Comment by bernstei** [comment]
Fine by me, certainly.  Maybe there should be a flag to make it overridable: for constraints that don't modify the nature of the affine deformation, e.g. bond lengths for a molecular solid, I can imagine people wanting to leave them in place. The unrelaxed elastic constants may not be meaningful, but the relaxed ones probably would be.

**Comment by jameskermode** [comment]
Should be fixed now. Please reopen if not.
