### ISSUE TITLE
rare crash in neighbor list

### ISSUE THREAD

**Issue by bernstei** [libAtoms/matscipy#47]
Very rarely, I get a crash inside matscipy's neighbor list code.  The crash happens in `neighbours.c`, specifically in
```c
PyObject *py_ret = PyTuple_New(strlen(quantities));
```
I added earlier references to `strlen(quantities)`, and they work until you get to
```c
#if PY_MAJOR_VERSION >= 3
    Py_DECREF(py_bquantities);
#endif
```
Indeed, `quantities` is set by what looks to me like it could just be a reference to the incoming python object, not a copy
```c
#if PY_MAJOR_VERSION >= 3
    PyObject *py_bquantities = PyUnicode_AsASCIIString(py_quantities);
    char *quantities = PyBytes_AS_STRING(py_bquantities);
#else
    char *quantities = PyString_AS_STRING(py_quantities);
#endif
```
If the `Py_DECREF` makes the pointer invalid (python documentation suggests that it can, from what I can tell), that would explain why accessing later sometimes leads to a seg fault.  Should it be copied, or move the `PyDECREF`  to later in the routine, once `quantities` is no longer needed?

**Comment by jameskermode** [comment]
Interesting, it does seem like there's a problem if the segfault occurs when accessing `quantitites`. 

However, according to [the docs](https://docs.python.org/3/c-api/unicode.html#c.PyUnicode_AsASCIIString) `PyUnicode_AsASCIIString` returns a new reference, so the code should actually be correct as it is. `PyBytes_AS_STRING` does not create a copy, it just interprets the pointer.

In any case, would you be willing to try moving the `Py_DECREF` after the last access to `quantitites` and see if this fixes the issue with your test case?

**Comment by jameskermode** [comment]
@pastewka do you think there's an issue with reference counting here?

**Comment by pastewka** [comment]
Should be fixed with this commit. `Py_DECREF` releases the buffer which `quantities` points to and of course needs to happen at the end. Thanks for reporting this @bernstei

**Comment by bernstei** [comment]
Thanks for the quick fix.  At what point does this change make it into the pypi version, or do I need to install from the github source?

**Comment by pastewka** [comment]
I just pushed it to PyPI
