### ISSUE TITLE
Segfault in an extreme case

### ISSUE THREAD

**Issue by cortner** [libAtoms/matscipy#5]
I got the following segfault during the test, which it looks like it is cause by theneighbourlist?

```
julia(98489,0x7fff72062000) malloc: *** mach_vm_map(size=18446744072217231360) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug
julia(98489,0x7fff72062000) malloc: *** mach_vm_map(size=18446744072217231360) failed (error code=3)
*** error: can't allocate region
*** set a breakpoint in malloc_error_break to debug

signal (11): Segmentation fault: 11
while loading /Users/ortner/.julia/v0.5/JuLIP/test/testvarcell.jl, in expression starting on line 68
py_neighbour_list at /Users/ortner/anaconda/lib/python2.7/site-packages/_matscipy.so (unknown line)
```

This is reproducible: it happens when I put too much (negative??) pressure on a cell so that it breaks all bonds and the cell starts expanding without bounds. Here is the sequence of cell matrices before the segfault: 
```
F = [0.0 4.05 4.05; 4.05 0.0 4.05; 4.05 4.05 0.0]
F = [-344.689 348.739 348.739; 348.739 -344.689 348.739; 348.739 348.739 -344.689]
F = [-1723.45 1727.5 1727.5; 1727.5 -1723.45 1727.5; 1727.5 1727.5 -1723.45]
F = [-8617.23 8621.28 8621.28; 8621.28 -8617.23 8621.28; 8621.28 8621.28 -8617.23]
```

Maybe you don't want to treat it as a bug at all, but I was just wondering whether a more gentle mode of failure (e.g. throw an exception) would be possible.

**Comment by pastewka** [comment]
Hi Christoph,

This looks like a bug and should be fixed.

Can you Post an atomic configuration (e.g. extxyz file) that reproduces this. I will then fix it.

Best,
Lars

**Comment by cortner** [comment]
sorry for the delay - I will post something.

**Comment by cortner** [comment]
here is a Python code that reproduces the crash. It is kind of a ridiculous example...
```python
import ase.build
at = ase.build.bulk("Al", cubic=True)
at.cell = at.cell * 8000
import matscipy.neighbours
matscipy.neighbours.neighbour_list("ijdDS", at, 4.5);
```

**Comment by pastewka** [comment]
I just pushed a fix for this. It was related to an integer overflow in the total number of cells used for the neighbor list search. Your example now runs, but it having lots of vacuum will be super-slow at some point.

**Comment by cortner** [comment]
Maybe print a warning or even a useful error message?

**Comment by pastewka** [comment]
Will add a warning. Did you check whether it fixes the problem that occured in your Julia code?

**Comment by pastewka** [comment]
Code is now issuing a warning in that situation.

**Comment by cortner** [comment]
yep - all working as expected.

**Comment by cortner** [comment]
thank you!
