### ISSUE TITLE
matscipy support windows?

### ISSUE THREAD

**Issue by futureflsl** [libAtoms/matscipy#57]
when I pip install matscipy with windows10 VS2019,errors occurred

  ERROR: Command errored out with exit status 1:
   command: 'D:\program\Anaconda3\envs\tmp\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-8ief1gm9\\matscipy\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-8ief1gm9\\matscipy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-wheel-hhahycjt'
       cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-8ief1gm9\matscipy\
  Complete output (142 lines):
  running bdist_wheel
  running build
  running config_cc
  unifing config_cc, config, build_clib, build_ext, build commands --compiler options
  running config_fc
  unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
  running build_src
  build_src
  building extension "_matscipy" sources
  build_src: building npy-pkg config files
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\matscipy
  copying matscipy\angle_distribution.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\atomic_strain.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\deformation.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\dislocation.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\distributed_computation.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\drift.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\elasticity.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\hessian_finite_differences.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\hydrogenate.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\logger.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\neighbours.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\opls.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\pressurecoupling.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\rings.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\socketcalc.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\spatial_correlation_function.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\surface.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\visualise.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\_version.py -> build\lib.win-amd64-3.7\matscipy
  copying matscipy\__init__.py -> build\lib.win-amd64-3.7\matscipy
  creating build\lib.win-amd64-3.7\matscipy\fracture_mechanics
  copying matscipy\fracture_mechanics\clusters.py -> build\lib.win-amd64-3.7\matscipy\fracture_mechanics
  copying matscipy\fracture_mechanics\crack.py -> build\lib.win-amd64-3.7\matscipy\fracture_mechanics
  copying matscipy\fracture_mechanics\crackpathsel.py -> build\lib.win-amd64-3.7\matscipy\fracture_mechanics
  copying matscipy\fracture_mechanics\energy_release.py -> build\lib.win-amd64-3.7\matscipy\fracture_mechanics
  copying matscipy\fracture_mechanics\idealbrittlesolid.py -> build\lib.win-amd64-3.7\matscipy\fracture_mechanics
  copying matscipy\fracture_mechanics\__init__.py -> build\lib.win-amd64-3.7\matscipy\fracture_mechanics
  creating build\lib.win-amd64-3.7\matscipy\contact_mechanics
  copying matscipy\contact_mechanics\analysis.py -> build\lib.win-amd64-3.7\matscipy\contact_mechanics
  copying matscipy\contact_mechanics\DMT.py -> build\lib.win-amd64-3.7\matscipy\contact_mechanics
  copying matscipy\contact_mechanics\greens_function.py -> build\lib.win-amd64-3.7\matscipy\contact_mechanics
  copying matscipy\contact_mechanics\Hertz.py -> build\lib.win-amd64-3.7\matscipy\contact_mechanics
  copying matscipy\contact_mechanics\JKR.py -> build\lib.win-amd64-3.7\matscipy\contact_mechanics
  copying matscipy\contact_mechanics\__init__.py -> build\lib.win-amd64-3.7\matscipy\contact_mechanics
  creating build\lib.win-amd64-3.7\matscipy\electrochemistry
  copying matscipy\electrochemistry\continuous2discrete.py -> build\lib.win-amd64-3.7\matscipy\electrochemistry
  copying matscipy\electrochemistry\poisson_boltzmann_distribution.py -> build\lib.win-amd64-3.7\matscipy\electrochemistry
  copying matscipy\electrochemistry\poisson_nernst_planck_solver.py -> build\lib.win-amd64-3.7\matscipy\electrochemistry
  copying matscipy\electrochemistry\__init__.py -> build\lib.win-amd64-3.7\matscipy\electrochemistry
  creating build\lib.win-amd64-3.7\matscipy\calculators
  copying matscipy\calculators\fitting.py -> build\lib.win-amd64-3.7\matscipy\calculators
  copying matscipy\calculators\supercell_calculator.py -> build\lib.win-amd64-3.7\matscipy\calculators
  copying matscipy\calculators\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators
  creating build\lib.win-amd64-3.7\matscipy\calculators\eam
  copying matscipy\calculators\eam\average_atom.py -> build\lib.win-amd64-3.7\matscipy\calculators\eam
  copying matscipy\calculators\eam\calculator.py -> build\lib.win-amd64-3.7\matscipy\calculators\eam
  copying matscipy\calculators\eam\io.py -> build\lib.win-amd64-3.7\matscipy\calculators\eam
  copying matscipy\calculators\eam\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators\eam
  creating build\lib.win-amd64-3.7\matscipy\io
  copying matscipy\io\metis.py -> build\lib.win-amd64-3.7\matscipy\io
  copying matscipy\io\opls.py -> build\lib.win-amd64-3.7\matscipy\io
  copying matscipy\io\tbl.py -> build\lib.win-amd64-3.7\matscipy\io
  copying matscipy\io\__init__.py -> build\lib.win-amd64-3.7\matscipy\io
  creating build\lib.win-amd64-3.7\matscipy\tool
  copying matscipy\tool\plot.py -> build\lib.win-amd64-3.7\matscipy\tool
  copying matscipy\tool\__init__.py -> build\lib.win-amd64-3.7\matscipy\tool
  creating build\lib.win-amd64-3.7\matscipy\calculators\pair_potential
  copying matscipy\calculators\pair_potential\calculator.py -> build\lib.win-amd64-3.7\matscipy\calculators\pair_potential
  copying matscipy\calculators\pair_potential\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators\pair_potential
  creating build\lib.win-amd64-3.7\matscipy\calculators\polydisperse
  copying matscipy\calculators\polydisperse\calculator.py -> build\lib.win-amd64-3.7\matscipy\calculators\polydisperse
  copying matscipy\calculators\polydisperse\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators\polydisperse
  creating build\lib.win-amd64-3.7\matscipy\calculators\mcfm
  copying matscipy\calculators\mcfm\calculator.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm
  copying matscipy\calculators\mcfm\cluster_data.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm
  copying matscipy\calculators\mcfm\qm_cluster.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm
  copying matscipy\calculators\mcfm\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm
  creating build\lib.win-amd64-3.7\matscipy\calculators\mcfm\mcfm_parallel
  copying matscipy\calculators\mcfm\mcfm_parallel\mcfm_parallel_control.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\mcfm_parallel
  copying matscipy\calculators\mcfm\mcfm_parallel\mcfm_parallel_worker.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\mcfm_parallel
  copying matscipy\calculators\mcfm\mcfm_parallel\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\mcfm_parallel
  creating build\lib.win-amd64-3.7\matscipy\calculators\mcfm\neighbour_list_mcfm
  copying matscipy\calculators\mcfm\neighbour_list_mcfm\neighbour_list_base.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\neighbour_list_mcfm
  copying matscipy\calculators\mcfm\neighbour_list_mcfm\neighbour_list_mcfm.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\neighbour_list_mcfm
  copying matscipy\calculators\mcfm\neighbour_list_mcfm\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\neighbour_list_mcfm
  creating build\lib.win-amd64-3.7\matscipy\calculators\mcfm\qm_cluster_tools
  copying matscipy\calculators\mcfm\qm_cluster_tools\base_qm_cluster_tool.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\qm_cluster_tools
  copying matscipy\calculators\mcfm\qm_cluster_tools\qm_clustering_tool.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\qm_cluster_tools
  copying matscipy\calculators\mcfm\qm_cluster_tools\qm_flagging_tool.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\qm_cluster_tools
  copying matscipy\calculators\mcfm\qm_cluster_tools\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\qm_cluster_tools
  UPDATING build\lib.win-amd64-3.7\matscipy/_version.py
  set build\lib.win-amd64-3.7\matscipy/_version.py to '0.6.0'
  running build_ext
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  customize MSVCCompiler using build_ext_subclass
  No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
  customize MSVCCompiler
  Missing compiler_cxx fix for MSVCCompiler
  customize MSVCCompiler using build_ext_subclass
  building '_matscipy' extension
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-8ief1gm9\matscipy\setup.py", line 281, in <module>
      url="https://github.com/libAtoms/matscipy"
    File "D:\program\Anaconda3\envs\tmp\lib\site-packages\numpy\distutils\core.py", line 171, in setup
      return old_setup(**new_attr)
    File "D:\program\Anaconda3\envs\tmp\lib\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "D:\program\Anaconda3\envs\tmp\lib\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "D:\program\Anaconda3\envs\tmp\lib\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "D:\program\Anaconda3\envs\tmp\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\program\Anaconda3\envs\tmp\lib\site-packages\wheel\bdist_wheel.py", line 290, in run
      self.run_command('build')
    File "D:\program\Anaconda3\envs\tmp\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\program\Anaconda3\envs\tmp\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\program\Anaconda3\envs\tmp\lib\site-packages\numpy\distutils\command\build.py", line 47, in run
      old_build.run(self)
    File "D:\program\Anaconda3\envs\tmp\lib\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "D:\program\Anaconda3\envs\tmp\lib\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\program\Anaconda3\envs\tmp\lib\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\program\Anaconda3\envs\tmp\lib\site-packages\numpy\distutils\command\build_ext.py", line 261, in run
      self.build_extensions()
    File "D:\program\Anaconda3\envs\tmp\lib\distutils\command\build_ext.py", line 449, in build_extensions
      self._build_extensions_serial()
    File "D:\program\Anaconda3\envs\tmp\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-8ief1gm9\matscipy\setup.py", line 81, in build_extension
      c = os.path.basename(self.compiler.compiler[0])
  AttributeError: 'MSVCCompiler' object has no attribute 'compiler'
  ----------------------------------------
  ERROR: Failed building wheel for matscipy
  Running setup.py clean for matscipy
Failed to build matscipy
Installing collected packages: matscipy
    Running setup.py install for matscipy ... error
    ERROR: Command errored out with exit status 1:
     command: 'D:\program\Anaconda3\envs\tmp\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-8ief1gm9\\matscipy\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-8ief1gm9\\matscipy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-l0hegtj0\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\program\Anaconda3\envs\tmp\Include\matscipy'
         cwd: C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-8ief1gm9\matscipy\
    Complete output (146 lines):
    running install
    running build
    running config_cc
    unifing config_cc, config, build_clib, build_ext, build commands --compiler options
    running config_fc
    unifing config_fc, config, build_clib, build_ext, build commands --fcompiler options
    running build_src
    build_src
    building extension "_matscipy" sources
    build_src: building npy-pkg config files
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\matscipy
    copying matscipy\angle_distribution.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\atomic_strain.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\deformation.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\dislocation.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\distributed_computation.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\drift.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\elasticity.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\hessian_finite_differences.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\hydrogenate.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\logger.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\neighbours.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\opls.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\pressurecoupling.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\rings.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\socketcalc.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\spatial_correlation_function.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\surface.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\visualise.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\_version.py -> build\lib.win-amd64-3.7\matscipy
    copying matscipy\__init__.py -> build\lib.win-amd64-3.7\matscipy
    creating build\lib.win-amd64-3.7\matscipy\fracture_mechanics
    copying matscipy\fracture_mechanics\clusters.py -> build\lib.win-amd64-3.7\matscipy\fracture_mechanics
    copying matscipy\fracture_mechanics\crack.py -> build\lib.win-amd64-3.7\matscipy\fracture_mechanics
    copying matscipy\fracture_mechanics\crackpathsel.py -> build\lib.win-amd64-3.7\matscipy\fracture_mechanics
    copying matscipy\fracture_mechanics\energy_release.py -> build\lib.win-amd64-3.7\matscipy\fracture_mechanics
    copying matscipy\fracture_mechanics\idealbrittlesolid.py -> build\lib.win-amd64-3.7\matscipy\fracture_mechanics
    copying matscipy\fracture_mechanics\__init__.py -> build\lib.win-amd64-3.7\matscipy\fracture_mechanics
    creating build\lib.win-amd64-3.7\matscipy\contact_mechanics
    copying matscipy\contact_mechanics\analysis.py -> build\lib.win-amd64-3.7\matscipy\contact_mechanics
    copying matscipy\contact_mechanics\DMT.py -> build\lib.win-amd64-3.7\matscipy\contact_mechanics
    copying matscipy\contact_mechanics\greens_function.py -> build\lib.win-amd64-3.7\matscipy\contact_mechanics
    copying matscipy\contact_mechanics\Hertz.py -> build\lib.win-amd64-3.7\matscipy\contact_mechanics
    copying matscipy\contact_mechanics\JKR.py -> build\lib.win-amd64-3.7\matscipy\contact_mechanics
    copying matscipy\contact_mechanics\__init__.py -> build\lib.win-amd64-3.7\matscipy\contact_mechanics
    creating build\lib.win-amd64-3.7\matscipy\electrochemistry
    copying matscipy\electrochemistry\continuous2discrete.py -> build\lib.win-amd64-3.7\matscipy\electrochemistry
    copying matscipy\electrochemistry\poisson_boltzmann_distribution.py -> build\lib.win-amd64-3.7\matscipy\electrochemistry
    copying matscipy\electrochemistry\poisson_nernst_planck_solver.py -> build\lib.win-amd64-3.7\matscipy\electrochemistry
    copying matscipy\electrochemistry\__init__.py -> build\lib.win-amd64-3.7\matscipy\electrochemistry
    creating build\lib.win-amd64-3.7\matscipy\calculators
    copying matscipy\calculators\fitting.py -> build\lib.win-amd64-3.7\matscipy\calculators
    copying matscipy\calculators\supercell_calculator.py -> build\lib.win-amd64-3.7\matscipy\calculators
    copying matscipy\calculators\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators
    creating build\lib.win-amd64-3.7\matscipy\calculators\eam
    copying matscipy\calculators\eam\average_atom.py -> build\lib.win-amd64-3.7\matscipy\calculators\eam
    copying matscipy\calculators\eam\calculator.py -> build\lib.win-amd64-3.7\matscipy\calculators\eam
    copying matscipy\calculators\eam\io.py -> build\lib.win-amd64-3.7\matscipy\calculators\eam
    copying matscipy\calculators\eam\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators\eam
    creating build\lib.win-amd64-3.7\matscipy\io
    copying matscipy\io\metis.py -> build\lib.win-amd64-3.7\matscipy\io
    copying matscipy\io\opls.py -> build\lib.win-amd64-3.7\matscipy\io
    copying matscipy\io\tbl.py -> build\lib.win-amd64-3.7\matscipy\io
    copying matscipy\io\__init__.py -> build\lib.win-amd64-3.7\matscipy\io
    creating build\lib.win-amd64-3.7\matscipy\tool
    copying matscipy\tool\plot.py -> build\lib.win-amd64-3.7\matscipy\tool
    copying matscipy\tool\__init__.py -> build\lib.win-amd64-3.7\matscipy\tool
    creating build\lib.win-amd64-3.7\matscipy\calculators\pair_potential
    copying matscipy\calculators\pair_potential\calculator.py -> build\lib.win-amd64-3.7\matscipy\calculators\pair_potential
    copying matscipy\calculators\pair_potential\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators\pair_potential
    creating build\lib.win-amd64-3.7\matscipy\calculators\polydisperse
    copying matscipy\calculators\polydisperse\calculator.py -> build\lib.win-amd64-3.7\matscipy\calculators\polydisperse
    copying matscipy\calculators\polydisperse\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators\polydisperse
    creating build\lib.win-amd64-3.7\matscipy\calculators\mcfm
    copying matscipy\calculators\mcfm\calculator.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm
    copying matscipy\calculators\mcfm\cluster_data.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm
    copying matscipy\calculators\mcfm\qm_cluster.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm
    copying matscipy\calculators\mcfm\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm
    creating build\lib.win-amd64-3.7\matscipy\calculators\mcfm\mcfm_parallel
    copying matscipy\calculators\mcfm\mcfm_parallel\mcfm_parallel_control.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\mcfm_parallel
    copying matscipy\calculators\mcfm\mcfm_parallel\mcfm_parallel_worker.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\mcfm_parallel
    copying matscipy\calculators\mcfm\mcfm_parallel\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\mcfm_parallel
    creating build\lib.win-amd64-3.7\matscipy\calculators\mcfm\neighbour_list_mcfm
    copying matscipy\calculators\mcfm\neighbour_list_mcfm\neighbour_list_base.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\neighbour_list_mcfm
    copying matscipy\calculators\mcfm\neighbour_list_mcfm\neighbour_list_mcfm.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\neighbour_list_mcfm
    copying matscipy\calculators\mcfm\neighbour_list_mcfm\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\neighbour_list_mcfm
    creating build\lib.win-amd64-3.7\matscipy\calculators\mcfm\qm_cluster_tools
    copying matscipy\calculators\mcfm\qm_cluster_tools\base_qm_cluster_tool.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\qm_cluster_tools
    copying matscipy\calculators\mcfm\qm_cluster_tools\qm_clustering_tool.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\qm_cluster_tools
    copying matscipy\calculators\mcfm\qm_cluster_tools\qm_flagging_tool.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\qm_cluster_tools
    copying matscipy\calculators\mcfm\qm_cluster_tools\__init__.py -> build\lib.win-amd64-3.7\matscipy\calculators\mcfm\qm_cluster_tools
    UPDATING build\lib.win-amd64-3.7\matscipy/_version.py
    set build\lib.win-amd64-3.7\matscipy/_version.py to '0.6.0'
    running build_ext
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    customize MSVCCompiler using build_ext_subclass
    No module named 'numpy.distutils._msvccompiler' in numpy.distutils; trying from distutils
    customize MSVCCompiler
    Missing compiler_cxx fix for MSVCCompiler
    customize MSVCCompiler using build_ext_subclass
    building '_matscipy' extension
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-8ief1gm9\matscipy\setup.py", line 281, in <module>
        url="https://github.com/libAtoms/matscipy"
      File "D:\program\Anaconda3\envs\tmp\lib\site-packages\numpy\distutils\core.py", line 171, in setup
        return old_setup(**new_attr)
      File "D:\program\Anaconda3\envs\tmp\lib\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "D:\program\Anaconda3\envs\tmp\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "D:\program\Anaconda3\envs\tmp\lib\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "D:\program\Anaconda3\envs\tmp\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "D:\program\Anaconda3\envs\tmp\lib\site-packages\numpy\distutils\command\install.py", line 62, in run
        r = self.setuptools_run()
      File "D:\program\Anaconda3\envs\tmp\lib\site-packages\numpy\distutils\command\install.py", line 36, in setuptools_run
        return distutils_install.run(self)
      File "D:\program\Anaconda3\envs\tmp\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "D:\program\Anaconda3\envs\tmp\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\program\Anaconda3\envs\tmp\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "D:\program\Anaconda3\envs\tmp\lib\site-packages\numpy\distutils\command\build.py", line 47, in run
        old_build.run(self)
      File "D:\program\Anaconda3\envs\tmp\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "D:\program\Anaconda3\envs\tmp\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\program\Anaconda3\envs\tmp\lib\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "D:\program\Anaconda3\envs\tmp\lib\site-packages\numpy\distutils\command\build_ext.py", line 261, in run
        self.build_extensions()
      File "D:\program\Anaconda3\envs\tmp\lib\distutils\command\build_ext.py", line 449, in build_extensions
        self._build_extensions_serial()
      File "D:\program\Anaconda3\envs\tmp\lib\distutils\command\build_ext.py", line 474, in _build_extensions_serial
        self.build_extension(ext)
      File "C:\Users\ADMINI~1\AppData\Local\Temp\pip-install-8ief1gm9\matscipy\setup.py", line 81, in build_extension
        c = os.path.basename(self.compiler.compiler[0])
    AttributeError: 'MSVCCompiler' object has no attribute 'compiler'
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\program\Anaconda3\envs\tmp\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-8ief1gm9\\matscipy\\setup.py'"'"'; __file__='"'"'C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\pip-install-8ief1gm9\\matscipy\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\ADMINI~1\AppData\Local\Temp\pip-record-l0hegtj0\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\program\Anaconda3\envs\tmp\Include\matscipy' Check the logs for full command output.

**Comment by pastewka** [comment]
Looks to me like it is not finding a compiler. My suggestion is use the Windows Subsystem for Linux (WSL) if you need to run this on Windows.

**Comment by pastewka** [comment]
I am closing this since we are unlikely to act on it.
