### ISSUE TITLE
Migrate CI to GitHub Actions?

### ISSUE THREAD

**Issue by jameskermode** [libAtoms/matscipy#76]
Travis-CI.org is shutting down imminently and the payment plans on the replacement Travis-CI.com are exorbitant, with no free open source plan any more. I think we need to follow the rest of the open source world to GitHub actions - would that be ok? Happy to try to migrate the travis.yml, as I'm doing the same for QUIP and friends.

**Comment by pastewka** [comment]
No objections

**Comment by jameskermode** [comment]
Looks like you've mostly done this already, to deploy docs to gh-pages and to PyPI. I guess we can just disable Travis, then.

**Comment by pastewka** [comment]
The automated tests are still in Travis I think.


________________________________
Von: James Kermode ***@***.***>
Gesendet: Donnerstag, 10. Juni 2021 11:33
An: libAtoms/matscipy
Cc: Lars Pastewka; Comment
Betreff: Re: [libAtoms/matscipy] Migrate CI to GitHub Actions? (#76)

**Comment by jameskermode** [comment]
Yup, just realised that. I've added a test stage to the GitHub Actions CI. Once that works I'll disable Travis to avoid duplicate notifications until it gets switched off next week.

**Comment by pastewka** [comment]
Sounds good!


________________________________
Von: James Kermode ***@***.***>
Gesendet: Donnerstag, 10. Juni 2021 11:38
An: libAtoms/matscipy
Cc: Lars Pastewka; Comment
Betreff: Re: [libAtoms/matscipy] Migrate CI to GitHub Actions? (#76)

**Comment by jameskermode** [comment]
Interestingly there are a couple of failing tests... wonder how long that's been the case. Not sure why they were all passing on Travis but not on GHA, must be some Python version thing. Will try to reproduce locally and fix.

**Comment by pastewka** [comment]
Oops...


________________________________
Von: James Kermode ***@***.***>
Gesendet: Donnerstag, 10. Juni 2021 12:54
An: libAtoms/matscipy
Cc: Lars Pastewka; Comment
Betreff: Re: [libAtoms/matscipy] Migrate CI to GitHub Actions? (#76)

**Comment by pastewka** [comment]
WIll be fixed once #77 is merged
