### ISSUE TITLE
c2d tests fail in CI

### ISSUE THREAD

**Issue by pastewka** [libAtoms/matscipy#78]
The following tests fail in CI:

* FAILED test_c2d.py::c2dCliTest::test_c2d_input_format_npz_output_format_xyz
* FAILED test_c2d.py::c2dCliTest::test_c2d_input_format_txt_output_format_xyz
* FAILED test_c2d.py::c2dCliTest::test_pnp_c2d_pipeline_mode

**Comment by jameskermode** [comment]
What is c2d?

**Comment by pastewka** [comment]
I think continous to discrete - it's a Poisson-Boltzmann solver but the naming is a bit unfortunate

@jotelha - can you fix this and think about a better naming scheme. Explicit is better than abbreviations in any case.

**Comment by jotelha** [comment]
This should make the tests work again as before, I will think about some explicit naming.
