### ISSUE TITLE
Add citation guide

### ISSUE THREAD

**Issue by ghost** [libAtoms/matscipy#94]
This is a brilliant project, many thanks for the help in researches.

How about adding a citation guide so that we can cite this repo?

**Comment by pastewka** [comment]
This is a good comment. @jameskermode - I'm not sure whether we'll be able to find time to write a paper on this. We could push releases to Zenodo and get DOI - hence become citable. (This will actually nicely show up on github as being citable.) That would be a minimal effort solution. Any thoughts?

**Comment by jameskermode** [comment]
It would be nice to write a matscipy paper but I agree it's unlikely to become high priority enough to happen, so also happy with a lower effort route. For QUIP we just added a [CITATION.cff](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/about-citation-files) file that links to the GitHub repo itself, which is even less work:

https://github.com/libAtoms/QUIP/blob/public/CITATION.cff

**Comment by jameskermode** [comment]
We have submitted a JOSS paper. It's not yet accepted, but hopefully it will be shortly. When it's available we can add a citation guide to the top-level README then close this issue.
